Add instantclient

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,6 +15,8 @@ ORACLE_CONFIG="${BUILD_DIR}/.oracle.yml"
 ORACLE_INSTANT_CLIENT_DIR="vendor/oracle_instantclient"
 ORACLE_INSTANT_CLIENT_URL="http://buildpacks.teresa-apps.io/oracle/oracle-instantclient-full-12.1-linux.x64.tar.gz"
 ORACLE_INSTANT_CLIENT_FILENAME=$(echo $ORACLE_INSTANT_CLIENT_URL | cut -d/ -f5)
+ORACLE_FILE_NAME = "instantclient.tar.gz"
+
 
 source "$BIN_DIR/utils"
 
@@ -23,33 +25,36 @@ puts-step "Found an .oracle.yml"
 indent "Making directory ${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR}"
 mkdir -p ${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR}
 
-indent "Downloading and extracting ${ORACLE_INSTANT_CLIENT_FILENAME}"
-curl ${ORACLE_INSTANT_CLIENT_URL} -L -s -o - | tar -xz -C \
-	${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR} -f -
+indent "Extracting $BASIC_FILENAME..."
+unzip $(pwd)/$ORACLE_FILE_NAME -d ${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR}
 
-if [[ $? != 0 ]]; then
-  indent "Failure while downloading Oracle instant client archive"
-  exit 1
-fi
+# indent "Downloading and extracting ${ORACLE_INSTANT_CLIENT_FILENAME}"
+# curl ${ORACLE_INSTANT_CLIENT_URL} -L -s -o - | tar -xz -C \
+# 	${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR} -f -
 
-indent "Successfully extracted ${ORACLE_INSTANT_CLIENT_FILENAME}"
+# if [[ $? != 0 ]]; then
+#   indent "Failure while downloading Oracle instant client archive"
+#   exit 1
+# fi
 
-ORACLE_NETWORK_ADMIN_DIR="${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR}/network/admin"
-mkdir -p ${ORACLE_NETWORK_ADMIN_DIR}
+# indent "Successfully extracted ${ORACLE_INSTANT_CLIENT_FILENAME}"
 
-if [[ -s $ORACLE_CONFIG ]]; then
-  TNSNAMES_FILENAME=$(grep tnsnames.ora $ORACLE_CONFIG | cut -d' ' -f2)
-  if [[ -f $BUILD_DIR/$TNSNAMES_FILENAME ]]; then
-    indent "Symlinking ${TNSNAMES_FILENAME} to ${ORACLE_INSTANT_CLIENT_DIR}/network/admin/tnsnames.ora"
-    ln -sf $BUILD_DIR/$TNSNAMES_FILENAME ${ORACLE_NETWORK_ADMIN_DIR}/tnsnames.ora
-  fi
+# ORACLE_NETWORK_ADMIN_DIR="${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR}/network/admin"
+# mkdir -p ${ORACLE_NETWORK_ADMIN_DIR}
 
-  SQLNET_FILENAME=$(grep sqlnet.ora $ORACLE_CONFIG | cut -d' ' -f2)
-  if [[ -f $BUILD_DIR/$SQLNET_FILENAME ]]; then
-    indent "Symlinking ${SQLNET_FILENAME} to ${ORACLE_INSTANT_CLIENT_DIR}/network/admin/sqlnet.ora"
-    ln -sf $BUILD_DIR/$SQLNET_FILENAME ${ORACLE_NETWORK_ADMIN_DIR}/sqlnet.ora
-  fi
-fi
+# if [[ -s $ORACLE_CONFIG ]]; then
+#   TNSNAMES_FILENAME=$(grep tnsnames.ora $ORACLE_CONFIG | cut -d' ' -f2)
+#   if [[ -f $BUILD_DIR/$TNSNAMES_FILENAME ]]; then
+#     indent "Symlinking ${TNSNAMES_FILENAME} to ${ORACLE_INSTANT_CLIENT_DIR}/network/admin/tnsnames.ora"
+#     ln -sf $BUILD_DIR/$TNSNAMES_FILENAME ${ORACLE_NETWORK_ADMIN_DIR}/tnsnames.ora
+#   fi
+
+#   SQLNET_FILENAME=$(grep sqlnet.ora $ORACLE_CONFIG | cut -d' ' -f2)
+#   if [[ -f $BUILD_DIR/$SQLNET_FILENAME ]]; then
+#     indent "Symlinking ${SQLNET_FILENAME} to ${ORACLE_INSTANT_CLIENT_DIR}/network/admin/sqlnet.ora"
+#     ln -sf $BUILD_DIR/$SQLNET_FILENAME ${ORACLE_NETWORK_ADMIN_DIR}/sqlnet.ora
+#   fi
+# fi
 
 ORACLE_HOME="${BUILD_DIR}/${ORACLE_INSTANT_CLIENT_DIR}"
 
